export {
  createMailRecipient,
  createMailScene,
  createMailSmtpConfig,
  deleteMailRecipient,
  deleteMailScene,
  deleteMailSmtpConfig,
  listMailRecipients,
  listMailScenes,
  listMailSmtpConfigs,
  testMailSmtpConfig,
  updateMailRecipient,
  updateMailScene,
  updateMailSmtpConfig,
} from '../features/mail/mail.api'
